Deploy a custom global pre-commit hook for git to check mail address

diff --git a/bin/git-default-config b/bin/git-default-config
--- a/bin/git-default-config
+++ b/bin/git-default-config
@@ -41,6 +41,9 @@ git config --global gc.auto 1
 # variable GIT_EDITOR is not set.
 git config --global core.editor $_edit
 
+# Add a private hook folder to the configurations
+git config --global init.templatedir "~/.git/templates"
+ 
 git config --global alias.aliases "!git config -l | grep alias | cut -c 7-"
 
 git config --global alias.r "remote -v"
@@ -185,5 +188,42 @@ Thumbs.db
 "
 
 echo "$_gitignore_global" > $HOME/.gitignore_global
+
+
+pre_commit=$(cat <<EOF
+#!/bin/sh
+
+EMAIL=\$(git config user.email)
+
+if [ -z "\$EMAIL" ] 
+then 
+  # user.email is empty
+  echo "ERROR: [pre-commit hook] Aborting commit because user.email is missing. Configure user.email for this repository by running: '$ git config user.email name@example.com'. Make sure not to configure globally and use the correct email."
+  exit 1
+fi
+
+exec < /dev/tty
+
+ans=n
+# user.email is not empty
+echo -n "Continue with user.email \$EMAIL (y/n): "
+read ans
+
+if [ "\$ans" = "y" ]
+then  
+  exit 0
+else
+  exit 1
+fi
+
+exit 0
+EOF
+)
+
+mkdir -p ~/.git/templates/hooks
+
+echo "$pre_commit" > ~/.git/templates/hooks/pre-commit
+
+chmod +x ~/.git/templates/hooks/pre-commit
 
 exit 0
