clean up

diff --git a/bin/password b/bin/password
--- a/bin/password
+++ b/bin/password
@@ -27,7 +27,7 @@ VERSION=0.1
 SCRIPT=${0##*/}
 
 # Help text for this script
-HELP="Usage: $SCRIPT (e)edit|(l)ist|(p)aste|(s)how [ARGUMENT]"
+HELP="Usage: $SCRIPT (e)edit|(l)ist|(p)aste|(s)how|(g)en [ARGUMENT]"
 
 # enable line numbers for debug output
 if [ "$_DEBUG" = "true" ] ; then
@@ -41,82 +41,64 @@ function _debug() {
 }
 
 function _error() {
-  echo 1>&2 "Error: $@"
-  echo "See \`$SCRIPT help\` for usage."
+        echo 1>&2 "Error: $@"
+        echo "$HELP"
+        exit 1
 }
 
-# Parse the command line options
-ARGS=$(getopt -o h -l "help" -- "$@")
-eval set -- "$ARGS"
-while true; do
-  case "$1" in
-    -h|--help)
-      _help
-      exit 0
-      ;;
-    --) shift; break ;;
-    *) break ;;
-  esac
+# make sure the dependency programs are installed
+for cmd in ccrypt xclip ; do
+        if ! command -v $cmd |: ; then
+                _error "$cmd not installed"
+        fi
 done
 
-if ! command -v ccrypt 2>&1 >/dev/null ; then
-	if command -v apt 2>&1 >/dev/null ; then
-		sudo apt -y install xclip ccrypt
-	fi
-	if command -v dnf 2>&1 >/dev/null ; then
-		sudo dnf -y install xclip ccrypt
-	fi
-	if command -v pacman 2>&1 >/dev/null ; then
-		sudo pacman -Sy xclip ccrypt
-	fi
-fi
-
-if [ -z "$PASSWORD_PATH" ]
-then
-  _error "PASSWORD_PATH not set!"
-  exit 1
-fi
+# check if the required environment variable is st
+[ -z "$PASSWORD_PATH" ] && _error "PASSWORD_PATH not set!"
 
 function list() {
-  ccrypt -c $PASSWORD_PATH | cut -d'|' -f1 | sed '/^ *$/d' | sort
+        ccrypt -c $PASSWORD_PATH | cut -d'|' -f1 | sed '/^ *$/d' | sort
 }
 
 function show() {
-  if [ -z "$1" ]
-  then
-    _error "Which password to show?"
-    exit 1
-  fi
-  echo $(ccrypt -c $PASSWORD_PATH | grep "^$1" | cut -d'|' -f2 | tr -d ' ' | tr -d '\n') 
+        [ -z "$1" ] &&  _error "Which password to show?"
+        echo $(ccrypt -c $PASSWORD_PATH | grep "^$1" | cut -d'|' -f2 | tr -d ' ' | tr -d '\n') 
 }
 
 function paste() {
-  echo $(show "$@") | xclip -selection clipboard
-  (sleep 30; echo '' | xclip -selection clipboard) &
+        # paste the password to the clipboard
+        echo $(show "$@") | xclip -selection clipboard
+        # empty the clipboard after 30 seconds
+        (sleep 30; echo '' | xclip -selection clipboard) &
 }
 
 function edit() {
-  ccrypt -d $PASSWORD_PATH
-  $EDITOR ${PASSWORD_PATH%.cpt}
-  ccrypt -e ${PASSWORD_PATH%.cpt}
+        ccrypt -d $PASSWORD_PATH
+        $EDITOR ${PASSWORD_PATH%.cpt}
+        ccrypt -e ${PASSWORD_PATH%.cpt}
 }
 
 
+#
+# Generate a random password
+#
 function gen() {
-  local num=${1:-10}
-  # get pseudo-random bytes as hex string
-  openssl rand -hex $num
+        # length of the password as first argument
+        local num=${1:-10}
+        num=$(( num/2 ))
+        # get pseudo-random bytes as hex string
+        openssl rand -hex $num
 }
 
 # Read the command-line arguments
 _command=$1 ; shift
 case "$_command" in 
-  list|l) list ;;
-  paste|p) paste "$@" ;;
-  show|s) show "$@" ;;
-  edit|e) edit ;;
-  gen|g) gen "$@" ;;
-  *) echo "$HELP" ;;
+        list|l) list ;;
+        paste|p) paste "$@" ;;
+        show|s) show "$@" ;;
+        edit|e) edit ;;
+        gen|g) gen "$@" ;;
+        *) echo "$HELP" ;;
 esac
 
 exit 0
